import { StyleDefine } from './type'

const proLabelConfig: Record<keyof StyleDefine, string> = {
  display: '布局方式',
  flexDirection: '主轴方向',
  flexWrap: '换行',
  gap: '子项间隙',
  gridAutoFlow: '主轴方向',
  justifyContent: '主轴对其方式',
  alignItems: '副轴对其方式',
  gridTemplate: '网格设置',
  gridGap: '子项间隙',
  flex: '弹性占比',
  width: '宽度',
  minWidth: '最小宽度',
  maxWidth: '最大宽度',
  height: '高度',
  minHeight: '最小高度',
  maxHeight: '最大高度',
  margin: '外边距',
  padding: '内边距',
  color: '文字颜色',
  opacity: '透明度',
  background: '背景',
  backgroundClip: '背景裁剪',
  filter: '滤镜',
  borderWidth: '边框线宽',
  borderStyle: '边框样式',
  borderColor: '边框颜色',
  borderRadius: '圆角',
  position: '定位',
  top: '上方距离',
  right: '右侧距离',
  bottom: '下方距离',
  left: '左侧距离',
  zIndex: '层级',
  outline: '外边框',
  fontSize: '字体大小',
  fontWeight: '字重',
  fontStyle: '字体样式',
  fontFamily: '字体',
  transform: '变换',
  transition: '过度',
  boxShadow: '阴影',
  boxSizing: '盒子模型',
  cursor: '鼠标',
  overflow: '溢出',
}

export default proLabelConfig
